runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
- .env

env_variables:
# Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:YuSUSDWb3V1UQAtNQlivezA6eJhBsui2SdSBrPwGIN8=
  STORAGE_DIR: /tmp
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: animus
  DB_USERNAME: root
  DB_PASSWORD: animus-dev-db
  DB_SOCKET: /cloudsql/animus-dev-205301:us-central1:animus-dev-db

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: animus-dev-205301:us-central1:animus-dev-db
  